### ISSUE TITLE
Hydration issue

### ISSUE THREAD

**Issue by Naught0** [RevoTale/next-scroll-restorer#54]
Edit: Looks like it's actually just mere presence of the `<Suspense>` which wraps the `ClientSideScrollRestorer` that causes a consistent hydration error. Based on the errors, I believe this will result in my whole application being client-side rendered

👋 Thanks for the great library! Works like a charm where the default nextjs implementation does not for me. However, I get a hydration error following the instructions in the readme

I have the following directory structure:

```
app/
├── components
│   ├── hooks
│   │   └── scroll-restore.tsx
└── layout.tsx
```

Using the hook from the readme:

```tsx
// app/components/hooks/scroll-restore.tsx
"use client";
import { useScrollRestorer } from "next-scroll-restorer";
export const ClientSideScrollRestorer = () => {
  useScrollRestorer();
  return <></>;
};
```

```tsx
// app/layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${jetbrains.variable}`}>
        <Analytics />
        <Providers>
          <Suspense>
            <Nav />
          </Suspense>
          <main className="flex min-h-screen flex-col items-center p-6 lg:p-12 xl:px-16">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
      <Suspense>
        <ClientSideScrollRestorer />
      </Suspense>
    </html>
  );
}
```

This works for scroll restoration, but I get hydration errors that disappear when I remove the hook from the layout:
![image](https://github.com/RevoTale/next-scroll-restorer/assets/4589250/1d861caa-db8f-43bd-bae4-fecb03e99bd2)

Everything still works fine, but I'm not sure if there are other negative ramifications as I'm relatively new to Next and RSCs, so figured I'd ask.

Cheers

**Comment by l-you** [comment]
Hello!
Could you please create a repository with minimal reproduction so I can debug error on my own?

**Comment by Naught0** [comment]
I cannot replicate this from a clean repo, so it's got to be my fault! Thanks again :)

**Comment by l-you** [comment]
You're welcome! :)
